# Generated by Django 4.0.3 on 2022-09-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='vegetables',
            field=models.TextField(default=None),
        ),
    ]
