# Generated by Django 4.0.3 on 2022-10-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_recipe_vegetables'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='bitter_gourd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='brinjal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='capsicum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='cauliflower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='chilly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='garlic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='ginger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='green_beans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='green_peas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='ladys_finger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='lemon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='pointed_gourd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='spong_gourd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='taro_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='tomato',
            field=models.BooleanField(default=False),
        ),
    ]
